import { StyleSheet, Platform } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: wp('5%'),
    paddingBottom: hp('2%'),
  },
  contentContainer: {
    flex: 1,
    paddingTop: hp('1%'),
  },
  title: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    textAlign: 'left',
    color: '#FFFFFF',
    marginBottom: hp('2%'),
  /* textShadow removed */
  },
  promo: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: wp('5%'),
    width: '100%',
    padding: wp('4%'),
    marginVertical: hp('1%'),
  /* shadow/elevation removed */
    borderWidth: 1,
    borderColor: 'rgba(0, 18, 51, 0.08)',
    backdropFilter: 'blur(20px)',
  },
  TextInput: {
    fontSize: wp('4.5%'),
    fontWeight: '800',
    marginBottom: hp('1%'),
    color: '#1E293B',
    letterSpacing: -0.3,
  },
  textHead: {
    fontSize: wp('4%'),
    fontWeight: '600',
    paddingVertical: hp('1%'),
    marginLeft: wp('2%'),
    color: '#374151',
    letterSpacing: 0.2,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('4%'),
    ...(Platform.OS === 'android' ? {} : {
      borderWidth: 1,
      borderColor: '#E5E7EB',
    }),
    borderRadius: wp('3%'),
    justifyContent: 'space-between',
    marginHorizontal: wp('2%'),
    marginBottom: hp('1%'),
  /* shadow/elevation removed */
  },
  buttonText: {
    fontSize: wp('4%'),
    color: '#374151',
    fontWeight: '500',
  },
  icon: {
    marginLeft: wp('2%'),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 18, 51, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContentPre: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    width: '80%',
    maxHeight: '50%',
    borderRadius: wp('4%'),
    padding: wp('4%'),
  /* shadow/elevation removed */
    ...(Platform.OS === 'android' ? {} : {
      borderWidth: 1,
      borderColor: 'rgba(0, 18, 51, 0.08)',
    }),
  },
  modalContent: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    width: '80%',
    height: '40%',
    borderRadius: wp('4%'),
    padding: wp('4%'),
  /* shadow/elevation removed */
    ...(Platform.OS === 'android' ? {} : {
      borderWidth: 1,
      borderColor: 'rgba(0, 18, 51, 0.08)',
    }),
  },
  optionItem: {
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('3%'),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    borderRadius: wp('2%'),
    marginBottom: hp('0.5%'),
  },
  optionText: {
    fontSize: wp('4%'),
    color: '#374151',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: '#E5E7EB',
    marginVertical: hp('1.5%'),
  },
  rowpromo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('0.5%'),
  },
  redText: {
    color: '#EF4444',
    fontWeight: '600',
  },
  promoLabel: {
    fontSize: wp('4.5%'),
    fontWeight: '800',
    marginBottom: hp('1%'),
    color: '#1E293B',
    letterSpacing: -0.3,
  },
  inputWrapper: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: wp('3%'),
    overflow: 'hidden',
    alignItems: 'center',
  /* shadow/elevation removed */
  },
  promoInput: {
    flex: 1,
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    fontSize: wp('4%'),
    backgroundColor: '#FFFFFF',
    color: '#374151',
  },
  applyButton: {
    backgroundColor: '#FD501E',
    paddingHorizontal: wp('5%'),
    justifyContent: 'center',
    alignItems: 'center',

    height: Platform.OS === 'android' ? hp('6.5%') : hp('6%'),
    borderTopRightRadius: wp('3%'),
    borderBottomRightRadius: wp('3%'),
  },
  applyText: {
    color: '#FFFFFF',
    fontSize: wp('4%'),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  input: {
    ...(Platform.OS === 'android' ? {} : {
      borderWidth: 1,
      borderColor: '#E5E7EB',
    }),
    borderRadius: wp('3%'),
    padding: wp('3%'),
    fontSize: wp('4%'),
    backgroundColor: '#FFFFFF',
    marginBottom: hp('1%'),
    paddingVertical: hp('1.5%'),
    marginHorizontal: wp('2%'),
    color: '#374151',
  /* shadow/elevation removed */
  },
  errorInput: {
    borderColor: '#EF4444',
    borderWidth: 2,
  /* shadow/elevation removed */
  },
  rowButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: hp('2%'),
    paddingHorizontal: wp('2%'),
  },
  BackButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingVertical: hp('2%'),
    borderRadius: wp('4%'),
    alignItems: 'center',
    marginTop: hp('1%'),
    width: '45%',
    marginBottom: hp('2%'),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  /* shadow/elevation removed */
  },
  BackButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: wp('4%'),
    letterSpacing: 0.5,
  },
  ActionButton: {
    backgroundColor: '#FD501E',
    paddingVertical: hp('2%'),
    borderRadius: wp('4%'),
    alignItems: 'center',
    marginTop: hp('1%'),
    width: '45%',
    marginBottom: hp('4%'),
  /* shadow/elevation removed */
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  searchButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: wp('4.5%'),
    letterSpacing: 0.5,
  /* textShadow removed */
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: wp('2%'),
    padding: wp('2%'),
    backgroundColor: '#FFFFFF',
    marginBottom: hp('1%'),
    color: '#374151',
    fontSize: wp('4%'),
  },
  disabledInput: {
    backgroundColor: '#F9FAFB',
    color: '#6B7280',
  },
  /* Ultra Premium styles for booking summary */
  premiumWrapper: {
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  premiumHeaderSimple: {
    backgroundColor: '#FD501E',
    borderTopLeftRadius: wp('4%'),
    borderTopRightRadius: wp('4%'),
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    alignItems: 'center',
  },
  premiumTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: wp('4.6%'),
    letterSpacing: -0.3,
  },
  premiumContent: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    borderBottomLeftRadius: wp('4%'),
    borderBottomRightRadius: wp('4%'),
    borderWidth: wp('0.08%'),
    borderColor: 'rgba(253,80,30,0.06)',
  },
  sectionHeading: {
    fontSize: wp('4%'),
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: hp('0.6%'),
  },
  routeText: {
    color: '#334155',
    fontSize: wp('3.6%'),
    marginBottom: hp('1%'),
  },
  premiumLabel: {
    color: '#64748B',
    fontWeight: '700',
    fontSize: wp('3.8%'),
  },
  premiumValue: {
    color: '#0F172A',
    fontWeight: '900',
    fontSize: wp('4%'),
  },
  premiumFare: {
    color: '#0F172A',
    fontWeight: '900',
    fontSize: wp('4.8%'),
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp('1%'),
  },
  totalLabel: {
    color: '#1E293B',
    fontWeight: '900',
    fontSize: wp('4%'),
  },
  totalValueBig: {
    color: '#B33E00',
    fontWeight: '900',
    fontSize: wp('5%'),
  },
  // Ultra Premium card styles (copied from TripDetailStyles for visual parity)
  premiumWrapper: {
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  premiumHeader: {
    width: '100%',
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    borderTopLeftRadius: wp('4%'),
    borderTopRightRadius: wp('4%'),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  premiumHeaderSimple: {
    backgroundColor: '#FD501E',
    borderTopLeftRadius: wp('4%'),
    borderTopRightRadius: wp('4%'),
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    alignItems: 'center',
  },
  premiumTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: wp('4.6%'),
    letterSpacing: -0.3,
  },
  premiumBadge: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    paddingVertical: hp('0.6%'),
    paddingHorizontal: wp('3%'),
    borderRadius: wp('6%'),
    borderWidth: wp('0.08%'),
    borderColor: 'rgba(255,255,255,0.18)',
  },
  premiumBadgeText: {
    color: '#FFF9F0',
    fontWeight: '900',
    fontSize: wp('3%'),
  },
  premiumContent: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('4%'),
    borderBottomLeftRadius: wp('4%'),
    borderBottomRightRadius: wp('4%'),
    borderWidth: wp('0.08%'),
    borderColor: 'rgba(253,80,30,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: hp('0.6%') },
    shadowOpacity: 0.06,
    shadowRadius: wp('2%'),
    elevation: 3,
  },
  sectionHeading: {
    fontSize: wp('4%'),
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: hp('0.6%'),
  },
  routeText: {
    color: '#334155',
    fontSize: wp('3.6%'),
    marginBottom: hp('1%'),
  },
  premiumLabel: {
    color: '#64748B',
    fontWeight: '700',
    fontSize: wp('3.8%'),
  },
  premiumValue: {
    color: '#0F172A',
    fontWeight: '900',
    fontSize: wp('4%'),
  },
  premiumFare: {
    color: '#0F172A',
    fontWeight: '900',
    fontSize: wp('4.8%'),
  },
  premiumTotalLabel: {
    color: '#334155',
    fontWeight: '900',
    fontSize: wp('4%'),
  },
  premiumTotalValue: {
    color: '#FD501E',
    fontWeight: '900',
    fontSize: wp('4.6%'),
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp('1%'),
  },
  totalLabel: {
    color: '#1E293B',
    fontWeight: '900',
    fontSize: wp('4%'),
  },
  totalValueBig: {
    color: '#B33E00',
    fontWeight: '900',
    fontSize: wp('5%'),
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: '#CCCCCC',
    marginVertical: 10,
  },
});
