import { StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: wp('5%'),
    paddingBottom: hp('2%'),
  },
  contentContainer: {
    flex: 1,
    paddingTop: hp('1%'),
  },
  title: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    textAlign: 'left',
    color: '#1E293B',
    marginBottom: hp('2%'),
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowRadius: 2,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: wp('5%'),
    width: '100%',
    padding: wp('4%'),
    marginVertical: hp('1%'),
    shadowColor: '#001233',
    shadowOpacity: 0.15,
    shadowRadius: wp('4%'),
    shadowOffset: { width: 0, height: hp('0.5%') },
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 18, 51, 0.08)',
    backdropFilter: 'blur(20px)',
  },
  header: {
    fontSize: wp('4.5%'),
    fontWeight: '800',
    marginBottom: hp('1%'),
    color: '#1E293B',
    letterSpacing: -0.3,
  },
  label: {
    fontSize: wp('4%'),
    marginBottom: hp('0.5%'),
    color: '#374151',
    fontWeight: '500',
  },
  labelHead: {
    fontSize: wp('4%'),
    marginBottom: hp('0.5%'),
    color: '#374151',
    fontWeight: '600',
  },
  input: {
    borderWidth: wp('0.2%'),
    borderColor: 'rgba(148, 163, 184, 0.3)',
    borderRadius: wp('3%'),
    padding: wp('3%'),
    fontSize: wp('4%'),
    backgroundColor: '#FFFFFF',
    marginBottom: hp('1%'),
    color: '#374151',
    shadowColor: '#6B7280',
    shadowOpacity: 0.08,
    shadowRadius: wp('2%'),
    shadowOffset: { width: 0, height: hp('0.3%') },
    elevation: 3,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('0.5%'),
  },
  rowpromo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('0.5%'),
  },
  redText: {
    color: '#FF0000',
  },
  inputContainer: {
    marginBottom: hp('1%'),
  },
  buttonContainer: {
    backgroundColor: '#FD501E',
    paddingVertical: hp('2%'),
    borderRadius: wp('4%'),
    alignItems: 'center',
    marginTop: hp('2%'),
    width: '100%',
    marginBottom: hp('4%'),
    shadowColor: '#FD501E',
    shadowOpacity: 0.4,
    shadowRadius: wp('3%'),
    shadowOffset: { width: 0, height: hp('0.5%') },
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp('1.5%'),
  },
  radioButton: {
    width: wp('5%'),
    height: wp('5%'),
    borderRadius: wp('2.5%'),
    borderWidth: 2,
    borderColor: '#E5E7EB',
    marginRight: wp('3%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedRadio: {
    backgroundColor: '#FD501E',
    borderColor: '#FD501E',
  },
  optionText: {
    fontSize: wp('4%'),
    color: '#374151',
  },
  payment: {
    marginTop: hp('2%'),
  },
  logodown: {
    flex: 1,
  },
  radioContian: {
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    borderRadius: wp('3%'),
    padding: wp('3%'),
    marginBottom: hp('1%'),
    backgroundColor: 'rgba(255,255,255,0.8)',
    shadowColor: '#6B7280',
    shadowOpacity: 0.08,
    shadowRadius: wp('2%'),
    shadowOffset: { width: 0, height: hp('0.3%') },
    // elevation: 3,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('1%'),
    marginBottom: hp('1%'),
  },
  textContainer: {
    flex: 1,
    marginLeft: wp('2%'),
  },
  textcolor: {
    color: '#FD501E',
    fontWeight: '600',
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: '#E5E7EB',
    marginVertical: hp('1.5%'),
  },
  // ...existing code...
  loadingContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)", // พื้นหลังโปร่งใส
    zIndex: 9999, // ✅ ให้ ActivityIndicator อยู่ด้านบนสุด
  },
  loadingText: {
    marginTop: 10,
    color: "#FFF",
    fontSize: 18,
  },
  inputWrapper: {
    position: 'relative',
    justifyContent: 'center',
    marginBottom: 20,
  },
  textInput: {
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingLeft: 15,
    paddingRight: 50, // ให้เว้นที่สำหรับ icon ด้านขวา
    fontSize: 16,
    backgroundColor: '#fff',
  },
  brandIcon: {
    position: 'absolute',
    right: 15,
    width: 45,
    height: 35,
  },
  BackButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: wp('4.5%'),
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowRadius: 1,
  },
  greenText: {
    color: '#10B981',
    fontWeight: '600',
  },
  // ...existing code...
  savedCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: wp('3%'),
    padding: wp('3.5%'),
    marginBottom: hp('1%'),
    borderWidth: wp('0.2%'),
    borderColor: 'rgba(148, 163, 184, 0.3)',
    shadowColor: '#6B7280',
    shadowOpacity: 0.08,
    shadowRadius: wp('2%'),
    shadowOffset: { width: 0, height: hp('0.3%') },
    elevation: 3,
  },
  selectedCard: {
    borderColor: '#FD501E',
    backgroundColor: 'rgba(253, 80, 30, 0.05)',
    shadowColor: '#FD501E',
    shadowOpacity: 0.15,
    shadowRadius: wp('3%'),
    shadowOffset: { width: 0, height: hp('0.5%') },
    elevation: 6,
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  savedCardIcon: {
    width: 38,
    height: 28,
    marginRight: 14,
    resizeMode: 'contain',
  },
  savedCardNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#002348',
  },
  savedCardName: {
    fontSize: 13,
    color: '#888',
    marginTop: 2,
  },
  addCardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FD501E',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.2%'),
    borderRadius: wp('2%'),
    alignSelf: 'flex-end',
    marginTop: hp('1%'),
    shadowColor: '#FD501E',
    shadowOpacity: 0.3,
    shadowRadius: wp('2%'),
    shadowOffset: { width: 0, height: hp('0.3%') },
    elevation: 6,
  },
  skeletonCard: {
    backgroundColor: '#ececec',
    borderRadius: 20,
    width: '100%',
    padding: 16,
    marginVertical: 16,
  },
  skeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  skeletonCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e0e0e0',
    marginRight: 10,
  },
  skeletonLineShort: {
    width: 120,
    height: 18,
    borderRadius: 8,
    backgroundColor: '#e0e0e0',
  },
  skeletonCardList: {
    marginTop: 10,
  },
  skeletonCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e8e8e8',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  skeletonCardIcon: {
    width: 38,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#d0d0d0',
    marginRight: 14,
  },
  skeletonLine: {
    width: '80%',
    height: 16,
    borderRadius: 8,
    backgroundColor: '#e0e0e0',
    marginBottom: 8,
  },
  skeletonLineSmall: {
    width: '50%',
    height: 12,
    borderRadius: 8,
    backgroundColor: '#e0e0e0',
    marginBottom: 8,
  },
  skeletonAddCardBtn: {
    width: 100,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#fdcdbb',
    alignSelf: 'flex-end',
    marginTop: 6,
  },
  skeletonButton: {
    width: '100%',
    height: 48,
    borderRadius: 10,
    backgroundColor: '#fdcdbb',
    marginTop: 20,
    marginBottom: 20,
  },
  
  // Banking Payment Styles
  bankSelectionContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: wp('3%'),
    padding: wp('4%'),
    marginTop: hp('1%'),
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  bankSelectionTitle: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: hp('1.5%'),
    textAlign: 'center',
  },
  bankGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: hp('2%'),
  },
  bankOptionCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: wp('2.5%'),
    borderWidth: 2,
    borderColor: '#E5E7EB',
    padding: wp('3%'),
    marginBottom: hp('1%'),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp('6%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedBankCard: {
    borderColor: '#FD501E',
    backgroundColor: '#FFF7F5',
    shadowColor: '#FD501E',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  bankOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  bankOptionText: {
    fontSize: wp('3.5%'),
    fontWeight: '500',
    color: '#374151',
    textAlign: 'center',
    flex: 1,
  },
  selectedBankText: {
    color: '#FD501E',
    fontWeight: '600',
  },
  bankCheckIcon: {
    marginLeft: wp('1%'),
  },
  bankingInfoContainer: {
    backgroundColor: '#F0F9FF',
    borderRadius: wp('2%'),
    padding: wp('3%'),
    borderLeftWidth: 4,
    borderLeftColor: '#FD501E',
  },
  bankingInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('0.8%'),
  },
  bankingInfoText: {
    fontSize: wp('3.2%'),
    color: '#475569',
    marginLeft: wp('2%'),
    flex: 1,
    lineHeight: wp('4.5%'),
  },
});

export default styles;
