import { StyleSheet, Platform } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: wp('5%'),
    paddingTop: hp('2%'),
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: wp('7%'),
    padding: wp('6%'),
    marginBottom: hp('2.5%'),
    shadowColor: '#001233',
    shadowOpacity: 0.25,
    shadowRadius: wp('8%'),
    shadowOffset: { width: 0, height: hp('1.5%') },
    elevation: 20,
    borderWidth: wp('0.3%'),
    borderColor: 'rgba(253, 80, 30, 0.12)',
    backdropFilter: 'blur(30px)',
  },
  companyHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp('2%'),
  },
  logoContainer: {
    marginRight: wp('4%'),
  },
  logo: {
    width: wp('20%'),
    height: wp('20%'),
    borderRadius: wp('2%'),
    backgroundColor: '#f5f5f5', // เพิ่ม background color กรณีรูปไม่โหลด
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  companyInfo: {
    flex: 1,
  },
  companyName: {
    fontSize: wp('5%'),
    fontWeight: '800',
    color: '#002348',
    marginBottom: hp('1%'),
    letterSpacing: -0.3,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('0.8%'),
  },
  infoText: {
    fontSize: wp('3.8%'),
    color: '#4B5563',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(148, 163, 184, 0.3)',
    marginVertical: hp('2%'),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  sectionTitle: {
    fontSize: wp('5%'),
    fontWeight: '800',
    color: '#002348',
    letterSpacing: -0.3,
  },
  dateText: {
    fontSize: wp('3.5%'),
    color: '#6B7280',
    fontWeight: '500',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp('1%'),
  },
  detailLabel: {
    fontSize: wp('4%'),
    color: '#4B5563',
    fontWeight: '500',
    flex: 1,
  },
  detailValue: {
    fontSize: wp('3%'),
    color: '#1F2937',
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  discountText: {
    fontSize: wp('3%'),
    color: '#EF4444',
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  feeText: {
    fontSize: wp('4%'),
    color: '#10B981',
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp('1.5%'),
    backgroundColor: 'rgba(253, 80, 30, 0.05)',
    borderRadius: wp('3%'),
    paddingHorizontal: wp('4%'),
  },
  totalLabel: {
    fontSize: wp('5%'),
    color: '#002348',
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  totalValue: {
    fontSize: wp('5.5%'),
    color: '#FD501E',
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  actionSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
  },
  bookingCodeSection: {
    flex: 1,
  },
  bookingLabel: {
    fontSize: wp('4%'),
    color: '#6B7280',
    fontWeight: '500',
    marginBottom: hp('0.5%'),
  },
  bookingCode: {
    fontSize: wp('4.5%'),
    color: '#002348',
    fontWeight: '800',
    letterSpacing: 1,
  },
  printButton: {
    borderRadius: wp('4%'),
    shadowColor: '#FD501E',
    shadowOpacity: 0.4,
    shadowRadius: wp('4%'),
    shadowOffset: { width: 0, height: hp('0.8%') },
    elevation: 12,
    marginLeft: wp('4%'),
  },
  printButtonGradient: {
    paddingVertical: hp('1.8%'),
    paddingHorizontal: wp('6%'),
    borderRadius: wp('4%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  printButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4%'),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  errorCard: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: wp('7%'),
    padding: wp('8%'),
    marginBottom: hp('2.5%'),
    shadowColor: '#EF4444',
    shadowOpacity: 0.25,
    shadowRadius: wp('8%'),
    shadowOffset: { width: 0, height: hp('1.5%') },
    elevation: 20,
    borderWidth: wp('0.3%'),
    borderColor: 'rgba(239, 68, 68, 0.12)',
    backdropFilter: 'blur(30px)',
  },
  errorContent: {
    alignItems: 'center',
  },
  errorTitle: {
    fontSize: wp('5.5%'),
    fontWeight: '800',
    color: '#DC2626',
    textAlign: 'center',
    marginBottom: hp('1%'),
    letterSpacing: -0.3,
  },
  errorSubtitle: {
    fontSize: wp('4.2%'),
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: hp('2%'),
    fontWeight: '500',
  },
  errorContact: {
    fontSize: wp('4%'),
    color: '#FD501E',
    fontWeight: '600',
    textAlign: 'center',
  },
  // เพิ่ม styles สำหรับส่วนคะแนน
  rewardSection: {
    marginTop: hp('2%'),
  },
  rewardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  rewardTitle: {
    fontSize: wp('5%'),
    fontWeight: '800',
    color: '#002348',
    marginLeft: wp('2%'),
    letterSpacing: -0.3,
  },
  rewardContainer: {
    borderRadius: wp('4%'),
    shadowColor: '#FFD700',
    shadowOpacity: 0.3,
    shadowRadius: wp('4%'),
    shadowOffset: { width: 0, height: hp('0.8%') },
    elevation: 10,
    marginBottom: hp('2%'),
  },
  rewardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('6%'),
    borderRadius: wp('4%'),
  },
  rewardContent: {
    flex: 1,
  },
  rewardPoints: {
    fontSize: wp('7%'),
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowRadius: 3,
    textShadowOffset: { width: 1, height: 1 },
  },
  rewardLabel: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#FFFFFF',
    opacity: 0.9,
    marginTop: hp('0.5%'),
  },
  rewardNote: {
    fontSize: wp('3.5%'),
    color: '#6B7280',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // เพิ่ม styles สำหรับส่วนแนะนำการ login
  loginPromptSection: {
    marginTop: hp('2%'),
  },
  loginPromptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  loginPromptTitle: {
    fontSize: wp('5%'),
    fontWeight: '800',
    color: '#6B7280',
    marginLeft: wp('2%'),
    letterSpacing: -0.3,
  },
  loginPromptContainer: {
    backgroundColor: 'rgba(107, 114, 128, 0.05)',
    borderRadius: wp('4%'),
    paddingVertical: hp('2.5%'),
    paddingHorizontal: wp('6%'),
    borderWidth: 1.5,
    borderColor: 'rgba(107, 114, 128, 0.15)',
    borderStyle: 'dashed',
  },
  loginPromptText: {
    fontSize: wp('4.2%'),
    color: '#6B7280',
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: hp('1%'),
    lineHeight: wp('5.5%'),
  },
  loginPromptSubtext: {
    fontSize: wp('3.5%'),
    color: '#9CA3AF',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: wp('4.5%'),
  },
});
